- id: epita-coding-style
  name: EPITA C/C++ Coding Style
  description: Validates C and C++ code against EPITA coding standards
  entry: epita-coding-style
  language: python
  files: \.(c|h|cc|hh|hxx|cpp|hpp)$
